# Generated by Django 4.1.2 on 2022-12-13 14:51

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_quill.fields.QuillField(blank=True, help_text='Может быть только один экземпляр!', null=True, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Страница "О нас"',
                'verbose_name_plural': 'Страница "О нас"',
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_quill.fields.QuillField(blank=True, help_text='Может быть только один экземпляр!', null=True, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Страница "Контакты"',
                'verbose_name_plural': 'Страница "Контакты"',
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_quill.fields.QuillField(blank=True, help_text='Может быть только один экземпляр!', null=True, verbose_name='Контент')),
                ('banner_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок в банере')),
                ('banner_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание в банере')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main_page_slider_images/', verbose_name='Картинка на слайдере')),
                ('main_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.mainpage')),
            ],
            options={
                'verbose_name': 'Картинка на слайдере',
                'verbose_name_plural': 'Картинки на слайдере',
            },
        ),
    ]
