# Generated by Django 4.1.2 on 2022-12-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='wp_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер WhatsApp'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='wp_text',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Текст для WhatsApp'),
        ),
    ]
