# Generated by Django 4.1.2 on 2022-12-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_mainpage_wp_number_mainpage_wp_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='wp_number',
            field=models.CharField(blank=True, help_text='Формат номера +770570570723', max_length=50, null=True, verbose_name='Номер WhatsApp'),
        ),
    ]
