# Generated by Django 4.1.2 on 2022-12-11 07:42

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название категории')),
                ('description', django_quill.fields.QuillField(blank=True, null=True, verbose_name='Описание категории')),
                ('slug', models.SlugField(blank=True, help_text='Если слаг не будет указан, он будет заполнен автоматически', max_length=200, null=True, unique=True, verbose_name='Слаг(название в ссылке)')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('description', django_quill.fields.QuillField(blank=True, null=True, verbose_name='Описание товара')),
                ('is_on_home_page', models.BooleanField(default=False, verbose_name='Будет ли данный продукт отображаться на главной')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Цена')),
                ('slug', models.SlugField(blank=True, help_text='Если слаг не будет указан, он будет заполнен автоматически', max_length=200, null=True, unique=True, verbose_name='Слаг(название в ссылке)')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Картинка')),
                ('is_cover', models.BooleanField(verbose_name='Обложка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
    ]
