# Generated by Django 4.1.2 on 2022-12-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыть продукт'),
        ),
    ]
